# config/facebook.yml
development:
  paypal_checkout_url: ""
  paypal_cancel_url: ""
  paypal_notify_url: ""
  paypal_id: ""
  
test:
  paypal_checkout_url: "https://www.paypal.com/cgi-bin/webscr"
  paypal_cancel_url: "https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=L2L5H5NK32QM4"
  paypal_notify_url: "http://test.checkpass.evangelize.jp/shop_admin/notify_url"
  paypal_id: "268Z9C7RWMCWQ"

production:
  paypal_checkout_url: "https://www.paypal.com/cgi-bin/webscr"
  paypal_cancel_url: "https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=L2L5H5NK32QM4"
  paypal_notify_url: "http://checkpass.evangelize.jp/shop_admin/notify_url"
  paypal_id: "XP57FP72GAD7A"


