# config/checkpass.yml
development:
  paypal_checkout_url: ""
  paypal_cancel_url: ""
  paypal_notify_url:  "http://localhost:3000/paypal/notify"
  paypal_id: "00000000"
  ex_top_image: "/assets/sample_top_image.png"
  ex_middle_image: "/assets/sample_middle_image.png"
  ex_coupon_image: "/assets/sample_coupon_image.gif"
  ex_wall_picture: "/assets/sample_wall_image.png"

test:
  paypal_checkout_url: "https://www.paypal.com/cgi-bin/webscr"
  paypal_cancel_url: "https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=L2L5H5NK32QM4"
  paypal_notify_url: "http://test.checkpass.jp/paypal/notify"
  paypal_id: "268Z9C7RWMCWQ"
  ex_top_image: "/assets/sample_top_image.png"
  ex_middle_image: "/assets/sample_middle_image.png"
  ex_coupon_image: "/assets/sample_coupon_image.gif"
  ex_wall_picture: "/assets/sample_wall_image.png"

production:
  paypal_checkout_url: "https://www.paypal.com/cgi-bin/webscr"
  paypal_cancel_url: "https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=C9EP7T9D7YEZJ"
  paypal_notify_url: "https://checkpass.jp/paypal/notify"
  paypal_id: "LMRPAEPYU8F6L"
  ex_top_image: "/assets/sample_top_image.png"
  ex_middle_image: "/assets/sample_middle_image.png"
  ex_coupon_image: "/assets/sample_coupon_image.gif"
  ex_wall_picture: "/assets/sample_wall_image.png"


